# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f1d6a3e585a85e64480a2f7c99c5e232b4941a20bc68561f7d8d7ebbde6f601de971a9ccf77ec342f1acd26fe6365414658e78e51363253c957d69d9e5bf20d

test:
  secret_key_base: 5f13883a8e5d9153bad6bc646e4979ee7cac3277029f681916bf8060926b3376601a01f4c43f57ea0121a8c82cc91e4280b45e09108d66e08f0570511ce19a95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
